BEGIN;
SET search_path = fear_temperature, public;

INSERT INTO research_version (
    research_version_id, version_label, status, seed_import_status,
    source_report, provenance_notes
) VALUES (
    'fear-temperature-quant-v0.1-provisional',
    'fear-temperature-quant-v0.1-provisional',
    'BLOCKED_FOR_INPUT_RECONCILIATION',
    'PARTIAL_RECONSTRUCTION',
    'Fear of Temperature — Historical Semantic Validation, Cross-Voice Relational Modelling, and Retrieval-Specification Freeze',
    'Provisional implementation seed. Original later-stage structured files and original later-stage candidate IDs were unavailable; reconstructed records must retain RECONSTRUCTED_FROM_REPORT provenance.'
) ON CONFLICT DO NOTHING;

INSERT INTO lexical_layer (layer_code, label, definition) VALUES
('A', 'Temperature / Physical Phenomenon', 'Measurement, thermal state, heat, warming, heatwaves, and physical thresholds.'),
('B', 'Climate / Atmospheric / Causal', 'Climate, atmosphere, carbon dioxide, greenhouse mechanism, and human attribution.'),
('C', 'Affect', 'Explicit or plausibly affective fear, worry, anxiety, concern, distress, and related states.'),
('D', 'Threat / Risk / Harm', 'Danger, threat, risk, crisis, mortality, damage, vulnerability, loss, and consequences.')
ON CONFLICT DO NOTHING;

INSERT INTO voice (voice_code, label, definition) VALUES
('V1', 'Scientific / Research', 'Scientists, researchers, scientific assessments, and research constructs.'),
('V2', 'Institutional / Governance', 'Governments, treaties, institutions, official assessments, and governance actors.'),
('V3', 'Mediated Public', 'Publication-generated or media-mediated public-facing discourse.'),
('V4', 'Organised Civic / Advocacy', 'Campaign, movement, protest, advocacy, and organised civic discourse.'),
('V5', 'Direct Public / Lay', 'Participant, worker, respondent, correspondent, or other lay/public voice.')
ON CONFLICT DO NOTHING;

INSERT INTO expression_mode (expression_mode_code, label, definition) VALUES
('E1', 'Direct / Spontaneous', 'Wording directly generated by the substantive speaker or documentary producer.'),
('E2', 'Quoted / Mediated', 'Wording quoted or transmitted through another documentary container.'),
('E3', 'Elicited', 'Wording or endorsement produced in response to a question, testimony prompt, or supplied instrument category.'),
('E4', 'Researcher-Coded / Researcher-Labelled', 'Analytical category, construct, or thematic label supplied by a researcher.'),
('E5', 'Not Applicable', 'Production-mode distinction does not apply or cannot meaningfully be assigned.')
ON CONFLICT DO NOTHING;

INSERT INTO review_outcome (review_outcome_code, is_acceptance, definition) VALUES
('ACCEPT', true, 'Valid evidence passage and semantic coding.'),
('ACCEPT_WITH_QUALIFICATION', true, 'Valid with an explicit sense, provenance, or comparability qualification.'),
('REJECT_FALSE_POSITIVE', false, 'Surface match is not relevant evidence.'),
('REJECT_WRONG_SENSE', false, 'Relevant spelling but an invalid historical or domain sense.'),
('REJECT_WRONG_DATE', false, 'Record falls outside the permitted date evidence window.'),
('REJECT_WRONG_VOICE', false, 'Substantive speaker does not match the required voice stratum.'),
('REJECT_INSUFFICIENT_CONTEXT', false, 'Available context cannot support a defensible classification.'),
('DUPLICATE', false, 'Duplicate manifestation or passage requiring preserved lineage rather than positive recounting.'),
('UNRESOLVED', false, 'Evidence or identity relationship remains unresolved.'),
('ESCALATE_FOR_ADJUDICATION', false, 'Boundary case requires additional independent review.')
ON CONFLICT DO NOTHING;

INSERT INTO source_genre (source_genre_code, label, definition) VALUES
('SCIENTIFIC', 'Scientific article / assessment', 'Scientific paper, assessment, measurement series, or scholarly research.'),
('INSTITUTIONAL', 'Institutional / legal / governance', 'Treaty, official report, inquiry, resolution, or governance document.'),
('MEDIA', 'Media', 'Newspaper, magazine, broadcast, or other mediated-public publication.'),
('SURVEY', 'Survey instrument / report', 'Survey question, response options, fieldwork report, or public-opinion analysis.'),
('DIRECT_PUBLIC', 'Testimony / letter / diary / direct public', 'Testimony, correspondence, diary, interview, or participant-generated material.'),
('CIVIC', 'Civic / advocacy', 'Campaign, association, protest, movement, or advocacy material.')
ON CONFLICT DO NOTHING;

INSERT INTO historical_anchor (
    anchor_id, label, strict_start, strict_end, contextual_start, contextual_end, definition, notes
) VALUES
('FT-A1842', '1842', '1842-01-01', '1842-12-31', '1839-01-01', '1845-12-31', 'Meteorological/environmental and embodied-heat baseline.', 'Not an origin point for anthropogenic climate fear.'),
('FT-A1938', '1938', '1938-01-01', '1938-12-31', '1936-01-01', '1940-12-31', 'Carbon-dioxide–temperature causal-science bridge.', 'Contemporary heat-event discourse is not evidence of reception of the scientific proposition.'),
('FT-A1988', '1988', '1988-01-01', '1988-12-31', '1986-01-01', '1990-12-31', 'Institutional climate-risk and mediated-warning anchor.', 'Strong V1/V2/V3 conjunction; exact-year V5 remains weak/not located.'),
('FT-A0607', '2006–2007', '2006-01-01', '2007-12-31', '2005-01-01', '2008-12-31', 'Public-communication and threat-framing bridge.', 'Preserves media-prescribed worry versus survey-elicited endorsement.'),
('FT-A2015', '2015', '2015-01-01', '2015-12-31', '2014-01-01', '2016-12-31', 'Temperature-threshold governance anchor.', 'Legal common concern is not personal emotion.'),
('FT-A2022', '2022', '2022-01-01', '2022-12-31', '2021-01-01', '2023-12-31', 'Contemporary heat/risk/affect endpoint.', 'Researcher, instrument, and participant language must remain separate.')
ON CONFLICT DO NOTHING;

INSERT INTO lexical_family (family_id, family_code, label, definition, primary_layer_code) VALUES
('FT-F01', 'temperature_threshold', 'Temperature / Threshold', 'Local/instrumental, mean, global aggregate, and governed threshold temperature senses.', 'A'),
('FT-F02', 'heat', 'Heat', 'Physical heat, embodied exposure, weather event, and extreme-heat hazard senses.', 'A'),
('FT-F03', 'warming', 'Warming', 'Temperature increase, climate-system warming, and global-warming issue-label senses.', 'A'),
('FT-F04', 'climate', 'Climate', 'Historical climatological condition, climatic change, modern climate change, climate system, and changing-atmosphere senses.', 'B'),
('FT-F05', 'carbon_greenhouse', 'Carbon / Greenhouse', 'Atmospheric carbon dioxide, anthropogenic production, greenhouse mechanism, and emissions framing.', 'B'),
('FT-F06', 'concern_alarm', 'Concern / Alarm', 'Personal concern, institutional evaluation, legal formula, and public-alarm senses.', 'C'),
('FT-F07', 'worry', 'Worry', 'Media-prescribed, instrument-supplied, participant-endorsed, and spontaneous worry functions.', 'C'),
('FT-F08', 'fear_afraid', 'Fear / Afraid', 'Direct fear, participant endorsement, supplied category, and historical negative-probe functions.', 'C'),
('FT-F09', 'anxiety', 'Anxiety', 'Anxious affect, symptom measure, climate-anxiety construct, eco-anxiety construct, and evidenced self-identification.', 'C'),
('FT-F10', 'distress_depression', 'Distress / Depression', 'Historical bodily/energetic depressing effect, modern psychological distress, and depressed affect.', 'C'),
('FT-F11', 'danger_threat', 'Danger / Threat', 'Hazard evaluation, institutional climate threat, personal/community threat appraisal, and security frame.', 'D'),
('FT-F12', 'risk', 'Risk', 'Probabilistic, economic, administrative, loss-and-damage, and personal perceived-risk senses.', 'D'),
('FT-F13', 'crisis_emergency', 'Crisis / Emergency', 'Severity predicate, climate-crisis label, emergency-response category, and climate-emergency declaration.', 'D'),
('FT-F14', 'harm_loss_consequences', 'Harm / Loss / Consequences', 'Bodily harm, mortality, damage, loss and damage, non-economic loss, vulnerability, and future-generation harm.', 'D')
ON CONFLICT DO NOTHING;

INSERT INTO pilot_sampling_plan (
    research_version_id, anchor_id, accepted_passage_target,
    v1_target, v2_target, v3_target, v4_target, v5_target, rationale
) VALUES
('fear-temperature-quant-v0.1-provisional', 'FT-A1842', 30, 12, 3, 3, 0, 12, 'Meteorological and worker/public evidence; no invented V4 stratum.'),
('fear-temperature-quant-v0.1-provisional', 'FT-A1938', 28, 16, 2, 10, 0, 0, 'Causal science plus heat-event journalism; no fabricated lay reception.'),
('fear-temperature-quant-v0.1-provisional', 'FT-A1988', 30, 12, 12, 6, 0, 0, 'Science/governance/media conjunction with exact-year V5 gap preserved.'),
('fear-temperature-quant-v0.1-provisional', 'FT-A0607', 36, 7, 7, 6, 4, 12, 'Cross-voice bridge with media imperative and elicited public worry kept distinct.'),
('fear-temperature-quant-v0.1-provisional', 'FT-A2015', 38, 4, 14, 5, 6, 9, 'Governance threshold and legal terminology plus recoverable civic/survey evidence.'),
('fear-temperature-quant-v0.1-provisional', 'FT-A2022', 38, 10, 6, 4, 4, 14, 'Dense affect/risk endpoint with construct/instrument/participant separation.' )
ON CONFLICT DO NOTHING;

INSERT INTO pilot_quality_metric_definition (
    metric_code, label, numerator_definition, denominator_definition, readiness_status, caution_note
) VALUES
('accepted_match_precision', 'Accepted-match precision', 'Accepted positive matches', 'All reviewed candidate matches', 'READY_FOR_REAL_DATA', 'No result is claimed before real reviewed passages exist.'),
('false_positive_rate', 'False-positive rate', 'REJECT_FALSE_POSITIVE decisions', 'All reviewed candidate matches', 'READY_FOR_REAL_DATA', 'Must be calculated from bounded collector output.'),
('wrong_sense_rate', 'Wrong-sense rate', 'REJECT_WRONG_SENSE decisions', 'All reviewed candidate matches', 'READY_FOR_REAL_DATA', 'Report by family and query rule.'),
('wrong_voice_rate', 'Wrong-voice rate', 'REJECT_WRONG_VOICE decisions', 'All reviewed candidate matches', 'READY_FOR_REAL_DATA', 'Source container and substantive speaker must be separate.'),
('insufficient_context_rate', 'Insufficient-context rate', 'REJECT_INSUFFICIENT_CONTEXT decisions', 'All reviewed candidate matches', 'READY_FOR_REAL_DATA', 'Context capture contract must be applied first.'),
('duplicate_rate', 'Duplicate rate', 'DUPLICATE decisions', 'All reviewed candidate matches', 'READY_FOR_REAL_DATA', 'Preserve manifestation/reuse lineage.'),
('provenance_completeness_rate', 'Provenance-completeness rate', 'Accepted positive passages with complete source/document/date/locator/voice/mode basis', 'All accepted positive passages', 'READY_FOR_REAL_DATA', 'Target is 100%; not yet measured.'),
('unresolved_rate', 'Unresolved rate', 'UNRESOLVED decisions', 'All reviewed candidate matches', 'READY_FOR_REAL_DATA', 'Systemic unresolved boundaries block scale-up.'),
('reviewer_agreement', 'Reviewer agreement', 'Independent matching categorical decisions', 'All independently double-coded decisions', 'READY_FOR_REAL_DATA', 'At least 50 pilot passages should be double-coded.'),
('family_specific_ambiguity_rate', 'Family-specific ambiguity rate', 'Wrong-sense, false-positive, and unresolved decisions within family', 'Reviewed matches within family', 'READY_FOR_REAL_DATA', 'Especially important for high-risk polysemous families.')
ON CONFLICT DO NOTHING;

COMMIT;
