"""Offline compact receipts from this changed tranche; no DB or old raw scan."""
import csv,json,statistics,re
from pathlib import Path
from collections import Counter,defaultdict
import transport as t
from review_saved import RIGHTS,PARTIAL

def csvsave(path,rows):
 path=t.OUT/path;path.parent.mkdir(parents=True,exist_ok=True)
 with path.open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=list(rows[0]),lineterminator='\n');w.writeheader();w.writerows(rows)
def main():
 cats=t.read(t.OUT/'control/CANDIDATES.json')['candidates'];cat={c['source_id']:c for c in cats};scope=t.read(t.SCOPE)
 requests=[t.read(p) for p in (t.OUT/'media/requests').glob('*.json')];gov=[t.read(p) for p in sorted((t.OUT/'government/attempts').glob('*.json'))]
 frames=[t.read(p) for p in sorted((t.OUT/'media/frames').glob('*.json'))];frame_by={(x['source_id'],x['month']):x for x in frames}
 articles=[];checks=[];variants=[];source_rows=[]
 for r in sorted([x for x in requests if x['purpose']=='body'],key=lambda x:x['requested_at_utc']):
  c=cat[r['source_id']];p=t.OUT/'media/parsed'/f"{r['request_id']}.json";a=t.read(p) if p.exists() else {};v=a.get('review',{})
  frame=frame_by[(c['source_id'],r['publication_month'])];ordinal=next(i+1 for i,x in enumerate(frame['selected']) if x['url']==r['request_url'])
  d=a.get('first_publication',{});native=a.get('first_publication_native_timestamp',d)
  row=dict(article_id='article22:'+r['request_id'],source_id=c['source_id'],stratum=c['stratum'],publisher_country=c['publisher_country'],edition=c['edition'],maps_original=c['maps_original'],original_source_success=False,frame_id=frame['frame_id'],selection_ordinal=ordinal,request_id=r['request_id'],request_url=r['request_url'],canonical_url=a.get('canonical_url',''),independent_parent_identity=a.get('canonical_url',r['request_url']),parent_independence='Publisher article identity only; underlying work independence unresolved for adoption/quotation',title=a.get('title',''),byline=v.get('byline',json.dumps(a.get('author'),ensure_ascii=False)),publication_month=r['publication_month'],publication_native_value=native.get('raw',''),publication_local_day=d.get('local_day',''),publication_precision=d.get('precision',''),publication_assignment=d.get('assignment_basis','Native publisher timestamp/date; no UTC-to-source reassignment asserted'),date_verified=bool(a.get('eligible_month')),retrieved_at_utc=r.get('finished_at_utc'),content_version_time=a.get('date_modified',{}).get('raw'),conflicting_modified_meta_values=json.dumps(a.get('date_modified_meta_values',[])),snapshot_time_utc=t.now().isoformat(),transport_status=r['status'],http_status=r['http_status'],unit_classification=a.get('unit_classification','complete_visible_html_article' if a.get('visible_body_verified') else 'HTTP_failure_unverified_article'),complete_visible_prose=bool(a.get('visible_body_verified')),embedded_component_completeness='Not claimed; images/audio/video not acquired',boundary_status=a.get('boundary_status','No saved complete raw article'),raw_path=r.get('raw_path',r.get('partial_path','')),raw_sha256=r.get('sha256',r.get('partial_sha256','')),raw_bytes=r['byte_count'],body_path=a.get('body_path',''),body_sha256=a.get('body_sha256',''),body_bytes=a.get('body_bytes',0),body_chars=a.get('body_chars',0),body_selector=a.get('body_selector',''),boundary_spec=json.dumps(a.get('body_boundary_spec')),directness=v.get('directness','direct publisher record/preview; underlying ownership unresolved'),originality=v.get('originality',a.get('inspection_note','unresolved')),rights_status=v.get('rights_status',RIGHTS.get(c['source_id'],'Saved source-specific policy; article grant unresolved')),historical_version_equivalence='Not established',climate_relevance='Not assessed',affect_risk_association='Not assessed',fear_interpretation='Not assessed')
  articles.append(row)
  checks.append(dict(request_id=r['request_id'],identity_verified=bool(a.get('request_identity_match')),publication_verified=bool(a.get('eligible_month')),source_edition_verified=bool(v.get('source_edition_verified')),rights_reviewed=bool(v.get('rights_reviewed')),complete_visible_prose=bool(a.get('visible_body_verified')),body_selector=a.get('body_selector'),boundary_spec=json.dumps(a.get('body_boundary_spec')),block_count=len(a.get('inspection_parts',[])),start_line_sha256=__import__('hashlib').sha256(a.get('body_text','').splitlines()[0].encode()).hexdigest() if a.get('body_text') else '',end_line_sha256=__import__('hashlib').sha256(a.get('body_text','').splitlines()[-1].encode()).hexdigest() if a.get('body_text') else '',inspection_note=v.get('inspection_note',a.get('inspection_note','HTTP failure; identity/date/body pending')),reviewed_at_utc=a.get('reviewed_at_utc',''),parser_sha256=a.get('parser_sha256','Initial parser receipt lacks explicit field; original preflight digests retained')))
  variants.append(dict(article_id=row['article_id'],variant_id='variant22:'+r['request_id'],kind='later_retrieved_publisher_HTML',retrieved_at_utc=r.get('finished_at_utc'),content_version_time=row['content_version_time'],raw_path=row['raw_path'],raw_sha256=row['raw_sha256'],derived_body_path=row['body_path'],derived_body_sha256=row['body_sha256'],historical_body_equality=False,original_slot_success=False))
 csvsave(Path('media/ARTICLE_MANIFEST.csv'),articles);csvsave(Path('media/BODY_BOUNDARY_CHECKS.csv'),checks);csvsave(Path('media/VARIANT_MANIFEST.csv'),variants)
 # Preserve original150 slot identities and explicitly separate candidate outcomes.
 slots=list(csv.DictReader((t.ROOT/'work_packages/M1_source_access/19_gov_closeout_and_media_transition_20261005/02_media_precollection/PILOT_SLOTS.csv').open()))
 mappings=[]
 for old in slots:
  c=next((x for x in cats if x['maps_original']==old['source_id']),None);f=frame_by.get((c['source_id'],old['month'])) if c else None;index=int(old['slot_index'])-1
  target=f['selected'][index]['url'] if f and index<len(f['selected']) else '';a=next((x for x in articles if x['request_url']==target),None)
  mappings.append(dict(original_slot_id=old['slot_id'],original_source_id=old['source_id'],stratum=old['region_layer'],month=old['month'],ordinal=old['slot_index'],original_status_preserved=old['status'],original_source_success=False,candidate_source_id=c['source_id'] if c else '',candidate_frame_id=f['frame_id'] if f else '',candidate_url=target,candidate_request_id=a['request_id'] if a else '',candidate_complete_visible_prose=a['complete_visible_prose'] if a else False,mapping_scope='Separate candidate coordinate; does not fill or validate original publisher',unfilled_state='candidate_verified_separately' if a and a['complete_visible_prose'] else a['unit_classification'] if a else 'selected_unattempted_after_route_stop' if target else 'No frozen eligible candidate target'))
 csvsave(Path('media/CANDIDATE_SLOT_MAPPING.csv'),mappings)
 quotas=[]
 for strat in ['EU_Europe','UK','AU','US','NZ']:
  for month in scope['original_months']:
   aa=[x for x in articles if x['stratum']==strat and x['publication_month']==month];ff=[x for x in frames if x['stratum']==strat and x['month']==month];n=sum(x['complete_visible_prose'] for x in aa)
   quotas.append(dict(stratum=strat,month=month,original_quota=10,original_publisher_verified=0,original_unfilled=10,candidate_sources_selected=len([x for x in cats if x['stratum']==strat]),frozen_candidate_targets=sum(len(x['selected']) for x in ff),candidate_body_attempts=len(aa),candidate_saved_raw=sum(x['transport_status']=='saved' for x in aa),candidate_verified_prose=n,candidate_unverified_attempts=len(aa)-n,candidate_unattempted_frozen=sum(len(x['selected']) for x in ff)-len(aa),planned_coordinates_without_verified_candidate=10-n,quota_transfer=0,monthly_denominator='Unknown; all frames bounded partial',inclusion_probability='Unknown'))
 csvsave(Path('media/QUOTA_TABLE.csv'),quotas)
 for c in cats:
  meta=[x for x in requests if x['source_id']==c['source_id'] and x['purpose']!='body'];meta_units=sum(max(1,len(x.get('hops',[]))) for x in meta);search=sum(x['request_url'].startswith('web-search:') for x in meta)
  for month in scope['original_months']:
   f=frame_by.get((c['source_id'],month));aa=[a for a in articles if a['source_id']==c['source_id'] and a['publication_month']==month]
   if int(month[:4])<c['founded_year']:state='Precedes declared candidate era; not attempted; not a publication zero'
   elif c['source_id']=='france24':state='Stopped: explicit AI-agent robots exclusions; no article target'
   elif f:state='Bounded partial frame; selected outcomes separately recorded'
   elif c['source_id']=='indaily':state='Era plausible but no month frame; discovery cap reached; older advertised shard ends2017'
   else:state='No bounded eligible month frame acquired; absence not inferred'
   source_rows.append(dict(source_version='round22_candidate_pre_body_v4',source_id=c['source_id'],stratum=c['stratum'],publisher_country=c['publisher_country'],edition=c['edition'],declared_founded_year=c['founded_year'],foundation_verification='Primary Our Story2014' if c['source_id']=='spinoff' else 'Primary About launch2009' if c['source_id']=='texastribune' else 'Accepted round20 identity evidence2017' if c['source_id']=='edjnet' else 'Declared candidate era; exact foundation date not newly independently verified',country_edition_verification='Primary About country/edition' if c['source_id'] in ['opendemocracy','indaily','texastribune'] else 'Primary NZ mission/offices and native edition' if c['source_id']=='spinoff' else 'Accepted Italian coordinator; member country pending' if c['source_id']=='edjnet' else 'UK market/native en-GB edition; legal HQ pending' if c['source_id']=='canary' else 'Primary About observed; body access prohibited',month=month,era_frame_state=state,frame_id=f['frame_id'] if f else '',frame_count=f['frame_count'] if f else '',selected_targets=len(f['selected']) if f else 0,body_attempts=len(aa),complete_visible_prose=sum(a['complete_visible_prose'] for a in aa),metadata_attempt_units=meta_units,search_responses=search,metadata_cap=20,search_cap=3,rights_state=RIGHTS.get(c['source_id'],'Accepted article/defaultCC BY4; graphics separate' if c['source_id']=='edjnet' else 'Accepted syndicationCC; article access account-gated' if c['source_id']=='opendemocracy' else 'Explicit robots AI exclusions; stopped'),retention='Local bounded evidence; licence uncertainty explicit',redistribution='No raw/text public export',maps_original=c['maps_original'],original_publisher_success=False))
 csvsave(Path('media/SOURCE_ERA_ACCESS.csv'),source_rows)
 # Newly changed government objects only; reuse saved local inspection, not old raw.
 observations=t.read(t.OUT/'government/evidence/inspection.json');oldledger=list(csv.DictReader((t.ROOT/'work_packages/M1_source_access/19_gov_closeout_and_media_transition_20261005/01_gov_closeout/continuation/FINAL_B_STATUS_LEDGER.csv').open()));oldhash={r['raw_sha256'] for r in oldledger if r['raw_sha256'] and r['latest_http_status']=='200'}
 govrows=[]
 docids={1:'OJ2015/C005/02',2:'SWD(2015)1final',3:'COM(2015)31final',4:'COM(2015)19final',5:'COM(2015)32final',6:'COM(2015)36final',7:'OJ2015/C17/04',8:'OJ2015/C8/06',9:'OJ2015/C11/08',10:'COM(2015)25final',11:'OJ2015/C014/04'}
 for r,o in zip(gov,observations):
  seq=o['sequence'];has_conflict=seq in {1,7,8,9,11};bodydate=r['publication_dates'];first=o['first_page'];from datetime import date
  dd=date.fromisoformat(bodydate);date_token=f'{dd.day}.{dd.month}.{dd.year}';assert date_token in first,(seq,date_token)
  govrows.append(dict(sequence=seq,request_id=r['request_id'],item_uri=r['item_uri'],parent_id=r['parent_id'],historical406_receipt=r.get('historical406_receipt') or '',request_accept='*/*',http_status=r['http_status'],redirects=len(r['hops'])-1,transport_status=r['status'],pdf_mime_signature_pass=True,raw_path=r['raw_path'],raw_sha256=r['sha256'],raw_bytes=r['byte_count'],distinct_new_hash=r['sha256'] not in oldhash,pages=o['pages'],nonempty_text_pages=sum(n>0 for n in o['page_text_chars']),text_chars=sum(o['page_text_chars']),printed_publication_date=bodydate,cdm_publication_date=r['publication_dates'],date_mapping='Printed cover/OJ issue date agrees; decision/event dates remain separate',observed_document_id=(re.search(r'(?:COM|SWD)\s*\(2015\)\s*\d+\s*final|\(2015/C\s*\d+/\d+\)',first).group(0) if re.search(r'(?:COM|SWD)\s*\(2015\)\s*\d+\s*final|\(2015/C\s*\d+/\d+\)',first) else 'Printed identifier pending'),identity_mapping='Exact requested Item saved; printed institution/document identifier inspected; WEMI relationship reuse only',observed_issuer='Riga District Court/Latvia notice in official EU archive' if seq==7 else 'European Commission/Official Journal; third-party statements separately scoped',genre_mapping='Inherited COM act_preparatory tag conflicts with observed OJ notice/list/application/communication; correction pending' if has_conflict else 'Observed Commission working document/report/reply/proposal; inherited generic tag needs refinement',provenance_check='conflicting inherited genre/issuer mapping' if has_conflict else 'verified exact Item/date/content shape; finer genre pending',directness='Official archival reproduction of recorded institutional publication; third-party rights/components unresolved',visual_check='First page rendered and inspected; all page text counts checked; no whole-document visual audit',local_text_path=f"government/evidence/{seq:02d}.txt",complete_pdf_object=True,complete_Work_verified=False,all_parent_components_verified=False,new_original_source=0,formal_ingestion=False,retrieved_at_utc=r['finished_at_utc'],http_last_modified=r['response_headers'].get('Last-Modified',''),pdf_creation_time=o['metadata'].get('creationDate',''),pdf_modification_time=o['metadata'].get('modDate',''),historical_content_equivalence='Not established'))
 csvsave(Path('government/TRANSPORT_AND_CHECK_LEDGER.csv'),govrows)
 nh={r['sha256'] for r in gov};t.save(t.OUT/'government/NEW_VERSION_SUMMARY.json',dict(historical_seal_preserved={'saved_Items':47,'failed':1,'unattempted':931,'distinct_raw_hashes':45,'denominator':979,'no_link_Works_outside_denominator':30,'new_originals':0},new_sequence={'saved_PDF_objects':len(gov),'distinct_new_hashes':len(nh),'overlap_prior_hashes':len(nh&oldhash),'bytes':sum(r['byte_count'] for r in gov),'date_agreements':11,'inherited_genre_conflicts':5,'whole_Works_verified':0,'originals':0,'formal_import':False},derived_candidate_queue={'saved_Items':58,'current_failed_transport':0,'unattempted':921,'distinct_raw_hashes':56,'denominator':979},not_new_parent_expansion=True,no_old_raw_rescan=True))
 # One raw row per physically retained object; shared search objects charged once.
 linked=defaultdict(list)
 for r in requests+gov:
  for k in ['raw_path','partial_path']:
   if r.get(k):linked[r[k]].append(r['request_id'])
 rawrows=[]
 for lane in ['media','government']:
  for p in sorted((t.OUT/lane/'raw').rglob('*')):
   if p.is_file():
    rel=str(p.relative_to(t.OUT));rawrows.append(dict(lane=lane,path=rel,bytes=p.stat().st_size,sha256=t.digest(p),request_ids=';'.join(sorted(set(linked[rel]))),kind='retained_partial' if p.suffix=='.part' else 'metadata_excerpt_capture' if 'metadata_excerpt' in p.name else 'saved_raw_or_public_search_response',remote_redistribution=False))
 csvsave(Path('RAW_MANIFEST.csv'),rawrows)
 good=[a for a in articles if a['complete_visible_prose']];newmedia=sum(p.stat().st_size for sub in ['raw','bodies','parsed','checks'] for p in (t.OUT/'media'/sub).rglob('*') if p.is_file())
 result=dict(at_utc=t.now().isoformat(),scope_publication_interval=scope['publication_interval'],original_publisher_articles_verified=0,original_unfilled_slots=150,candidate_sources=len(cats),candidate_frozen_targets=sum(len(f['selected']) for f in frames),body_attempts=len(articles),saved_article_raws=sum(a['transport_status']=='saved' for a in articles),verified_complete_visible_prose=len(good),preview_attempts=sum(a['unit_classification']=='account_gated_preview' for a in articles),readable_partial_secondary_or_component_units=sum(a['unit_classification'] in [v[0] for v in PARTIAL.values()] for a in articles),http_body_failures=sum(a['transport_status']!='saved' for a in articles),unattempted_selected=sum(len(f['selected']) for f in frames)-len(articles),first30minute_milestone=False,first30minute_verified=0,verified_by_stratum=dict(Counter(a['stratum'] for a in good)),verified_by_month=dict(Counter(a['publication_month'] for a in good)),body_length_diagnostics={'unit':'Complete visible article HTML prose at retrieval, including named structural qualifications','min_chars':min(a['body_chars'] for a in good),'median_chars':statistics.median(a['body_chars'] for a in good),'max_chars':max(a['body_chars'] for a in good),'length_selection':False,'whole_corpus_inference':False},new_media_retained_bytes=newmedia,media_lifetime_bytes=scope['accepted_media_prior_bytes']+newmedia,government_new_raw_bytes=sum(r['byte_count'] for r in gov),government_lifetime_raw_bytes=22231574+sum(r['byte_count'] for r in gov),network_closed=True,formal_database_access=False,private_evaluator_access=False,topic_affect_fear_analysis=False)
 t.save(t.OUT/'RESULT.json',result)
 # Recheck only registered public inputs; never locate external evaluator material.
 frozen=[]
 for r in t.read(t.OUT/'control/INPUT_RECEIPT.json')['files']:
  p=t.ROOT/r['path'];frozen.append(dict(path=r['path'],expected_sha256=r['sha256'],observed_sha256=t.digest(p),unchanged=t.digest(p)==r['sha256']))
 assert all(x['unchanged'] for x in frozen);t.save(t.OUT/'control/FROZEN_INPUT_RECHECK.json',dict(at_utc=t.now().isoformat(),files=frozen,passed=True,no_old_government_raw_read=True))
 t.save(t.OUT/'control/FINAL_STORAGE.json',t.budget());print(json.dumps(result,indent=2))
if __name__=='__main__':main()
