"""Factual final report for the allocated four-hour newspaper run."""
import collections

def report(s, genre_rows, frontier_rows, pending):
 f=s['focused_repair_priorities'];c=s['checks'];mix=s['new_regular_source_year_mix']
 lines=[
 '# Directed newspaper repair and acquisition — 11 October 2026','',
 f"This fixed four-hour window retained **{s['additional_regular_newspaper_IDs']:,} new complete regular-frame newspaper article IDs** and **{s['additional_supplementary_edition_IDs']:,} separately typed supplementary-edition article IDs**. The regular non-campus frame changed from {s['baseline_current_newspaper_IDs']:,} to **{s['current_newspaper_complete_IDs']:,} articles**. Its dated presence is **{s['observed_study_months']}/465 months**, with {s['remaining_empty_months']} regular-frame empty months. The {s['historical_campus_IDs_preserved']:,} campus article IDs remain preserved separately.",'',
 f"The coordinator bound this window after reviewing the closed eight-hour input. Its start was {s['earliest_authorized_network_and_load_start_at_utc']}; the hard deadline remained **{s['hard_deadline_at_utc']}**, including preparation and all controlled implementation handovers. The terminal reason is `{s['stop_reason']}`. Host-reported session exit, PID absence and lifetime-mutex availability are recorded in `TERMINAL_WRITER_EXIT.json`. No additional window is released.",'',
 'The publication interval remains **1988-01-01 through 2026-09-21**. September 2026 is partial. Publication dates, extraction/retrieval times, current content representations, archive transcription times and report timestamps remain separate; later retrieval does not prove a historical body version or end-of-day coverage.','',
 '## Repaired chain and real recovery','',
 'The inherited implementation suppressed general Green Left body opportunities, failed to extend the live ready overlay when an issue directory yielded new candidates, and dispatched one article before rotating. This window repaired those three paths in the new worker while preserving prior queue/raw states. Exact issue/year evidence now updates the ready overlay in the same process; generic eligible bodies outside the named legacy set remain executable. A bounded operation rechecks eligibility before each article and performs the normal per-article resource/source checks and durable Load. Eight is an operation bound, never a monthly quota or completion criterion.','',
 'The targeted chain checks passed: eight eligible same-month targets with two committed retain all remaining six; rerun adds none; interruption after the first durable article leaves five eligible; resume loads those five; newly parsed issue candidates become live body opportunities; independent date conflicts remain pending. A separate real bridge proof loaded eight new January 1994 native issue-127 articles while 75 ready candidates remained. Fixture SQL was isolated in memory; real production proceeded through the continuing newspaper store.','',
 f"Across the {f['legacy_GL_affected_months']} frozen legacy Green Left-only months, this window loaded **{f['named_legacy_new_IDs']:,} new articles in {f['legacy_GL_months_with_real_surplus']} months**. `LEGACY_AFFECTED_MONTH_BEFORE_AFTER.csv` distinguishes the bound eight-hour baseline from this window's actual additions. Original processed flags do not establish that article queues or archives are exhausted. Neither coverage counts nor the earlier four/five-record plateaus control production.",'',
 f"The coordinator's H2 metadata check found that issues 293–295, dated in October 1997, had yielded 70/60/57 live merged candidates but no body attempts. A normal operation-boundary handover added exact issue opportunities and preserved per-article cursors and waiting-age rotation. Their actual bridge results are **{s['fresh_issue_bridge']['actual_new_complete_IDs']} new complete article IDs**, with {s['fresh_issue_bridge']['pending_result_events']} preserved pending result events. `FRESH_ISSUE_TERMINAL_REGISTER.csv` records each dated issue's candidate/attempt/Load state and remaining cursor. Successful results were checked against the changed-tranche SQL/Load mapping; a directory's processed flag never substitutes for body exhaustion. Eight is a bounded operation size, without limiting any issue or month.", '',
 'Charlotte recovery used the exact ten IDs and self-document links in the saved smaller chronological listing. The earlier body-batch and page-two timeouts, pending rows and counters were retained. Only those named zero-response transport cases gained derived individual-document eligibility; no blanket status/cursor reset or host-stop bypass occurred. Successful current loads establish recovered bodies; the blocked pagination frontier still limits further discovery.','',
 'A batch-state preservation defect was also repaired: later batches persisted the derived eligibility-filtered map and omitted exactly ten inherited Charlotte rows from the new working view. Frozen original rows, receipts and the named manifest remained intact. The exact ten baseline rows were restored without changing any other current row; acquire and saved resume now persist raw status maps and filter only eligibility. Regression checks cover both paths. The final check verifies baseline status-ID membership and all named original status/request pairs.', '',
 'Kilkenny Observer also had an exact 25-unit zero-response ReadTimeout batch. Their original saved native ID/permalink/date/self metadata and zero consumed native response hops were verified. Individual source-advertised self documents were released as a derived alternative, while failed batch URLs, original pending rows, source stops and counters remain preserved. Actual recovered bodies are represented in the source/year table; this fallback does not claim archive completeness.', '',
 '## Opening months and supplementary editions','',
 f"The regular frame began with {f['baseline_empty_months']} empty months. Newly recovered regular-frame months: {', '.join(f['newly_present_baseline_empty_months']) or 'none'}. Remaining regular-frame gaps: **{', '.join(f['remaining_baseline_empty_months']) or 'none'}**. The Workers’ Advocate regular issue 18-11 index/masthead conflict remains pending; its November index and December masthead were not reconciled by guessing dates.",'',
 f"A separately evidenced Workers’ Advocate Supplement index and four matching title/volume/issue/day mastheads yielded {s['additional_supplementary_edition_IDs']} complete native anchored articles: " + '; '.join(f'{m}: {n}' for m,n in sorted(s['separate_supplementary_month_counts'].items())) + '. The native article boundaries, exact index/masthead dates and distinct supplement IDs are retained in `NEWSPAPER_SUPPLEMENT_ARTICLE_REGISTER.csv`. These are archival transcriptions/reproductions, with original-print/transcription equivalence and historical body version unverified.','',
 f"Supplementary articles are retained separately from `CURRENT_NEWSPAPER_ARTICLE_REGISTER.csv`. They add no independent conventional newspaper title and do not close regular-edition gaps by relabelling. `COMBINED_FAMILY_MONTHLY_PRESENCE.csv` provides an explicitly alternative combined family view with {s['combined_family_observed_months']}/465 dated months.",'',
 '## Actual contributing titles and observed eras','',
 f"Actual regular-frame contributing title IDs changed from {f['before_contributing_title_IDs']} to **{f['after_contributing_title_IDs']}**. Newly contributing titles are {', '.join(f['new_contributing_title_ids']) or 'none'}. Candidate names, admitted profiles, interfaces, parent families and supplementary editions are separate units. The 50-title development objective was neither a guaranteed yield nor a stopping gate.",'',
 '| Regular-frame source ID | New complete articles | Observed publication years |','| --- | ---: | --- |']
 for sid,years in sorted(mix.items()):lines.append(f"| {sid} | {sum(years.values()):,} | "+'; '.join(f'{y}: {n:,}' for y,n in sorted(years.items()))+' |')
 lines += ['',
 'The title profiles added to the executable frontier were Gippsland Times, Midland Express, Castlemaine Mail, The Chester Telegraph and Islington Tribune. The first three are regional/local newspaper titles; Chester is explicitly an online-only local newspaper, without a print-edition claim; Islington is a local weekly title. Actual contributions and earliest retained dates are established by loads above, not by classifications or founding dates. Their current publisher-group observations do not prove independent parents or historical ownership timelines.','',
 'A normal operation-boundary handover projected the exact saved root/schema evidence for these newly admitted profiles through the existing source adapters. All six remaining preparation steps reused saved receipts with zero additional HTTP attempts; the resulting native metadata/XML frontiers were recorded without manual cursor assignment, status reset or body Load. The writer resumed after PID absence/mutex proof and retained the same hard deadline and counters. Operational waiting ages were restored from last-selection rounds.', '',
 'For the four newly admitted WordPress titles, a native JSON article can qualify only when its body, title, publication date and original URL agree with the full currently visible unprotected publisher HTML. Paywalls/previews, public-access limits, date conflicts or body-version differences remain pending. This records current representation agreement, not historic-version equivalence. Islington uses the evidenced native Article__container HTML template and native sitemap routes.','',
 'The new publisher HTML mapper initially truncated a UTC publication timestamp to its calendar date. Six exact Midland cases had a unique visible timestamp with an explicit +11:00 offset, exactly matching the native API wall-clock publication timestamp and representing the same instant as the original UTC article:published_time. The changed mapper checks canonical identity, exact wall-clock/instant equality and unique offset evidence; it never assumes a country timezone or uses retrieval/lastmod dates. All six native bodies and visible-body hashes agreed and recovered through normal Load with zero new HTTP attempts. Their original publication days, pending events, batch states, raw and counters remain preserved. Genuine conflicts, absent offsets and ambiguous times remain pending.', '',
 f"Real saved-response template recovery retained {sum(r['load_status']=='confirmed_complete' for r in s['visible_template_saved_recovery'])} historical SQL/Load identities, of which {s['visible_template_recovery_current_qualified_IDs']} are qualified complete articles with zero new HTTP attempts; {sum(r['load_status']!='confirmed_complete' for r in s['visible_template_saved_recovery'])} named cases retained pending mapping results. Castlemaine and Gippsland body containers included image/content HTML comments, and the Castlemaine publisher explicitly hid a separate featured-image block with unconflicted local CSS. The structural mapper excludes only those invisible template artefacts and preserves visible captions and all article narrative. Chester uses its evidenced unique .post .entry container and excludes the separate #jp-relatedposts widget. Exact full-body/title/canonical/publication-date checks and paywall/access protections remain in force. Original HTML/JSON bytes and pending events are unchanged; derived cleanup facts and hashes are reproducible from raw. The 18 unmatched Gippsland cases have explicit MemberPress unauthorized-excerpt/login boundaries inside the article body and remain pending for access/completeness. Matching public JSON and HTML can also match a preview: one initially retained identity, gippsland_times:post:8980, has that exact source boundary. Its SQL text, native ID, version, raw, original Load event and counters remain preserved; only the derived complete-article membership is false. The other six recovered Gippsland bodies remain qualified. A guard now rejects explicit unauthorized-excerpt/login boundaries within the admitted body; header login outside the body does not trigger it. The original H3 snapshot remains preserved with a digest-bound correction.", '',
 'Broad purpose/genre/era metadata is structural. Native category IDs or section names remain separate from later semantic genre analysis. The table describes returned articles, not complete title archives. Dublin Gazette image-only units, compiled letters/calendars, ambiguous boundaries and conflicting dates remain explicit pending evidence. Berkeley carrier pages are containers; complete native story identity, date and body boundaries determine countable articles.','',
 '## Source quality and access limits','',
 'Original publisher articles are direct evidence of the recorded newspaper discourse. Archive transcriptions remain archival reproductions. Embedded reprints, quotations, letters and speaker attribution require passage-level checks; verifying provenance does not establish the truth of every claim. Direct/original, archival, indirect/secondary, mixed and unresolved evidence must remain distinguishable. Source identity/date/content verification, pending checks, conflicts and access limits are recorded separately in the provenance, frontier and pending registers.','',
 'Public access, collection/retention permission, open licensing and redistribution remain distinct. No unrestricted full-text redistribution licence is inferred. Wairarapa Times-Age explicit written-consent terms prevented article admission; robots/host stops prevented other named candidate routes. Trove automated consent, CSM truncation/paywall, Deseret policy, PapersPast challenge and all 36 consumed PDF slots remain protected. No private/account interfaces, permission applications or third-party messages were used.','',
 'The inherited Cambridge publisher template `cambridge_news_nz:article:194` remains in SQL with its ID, version, raw evidence and counters. Its exact prior structural disposition continues to exclude it from qualified views. No topic, language, length, climate, affect or fear threshold was substituted.','',
 '## Verification and terminal inventory','',
 f"Changed-tranche checks passed: **{c['all_passed']}**. SQLite quick-check: {c['SQLite_quick_check']}; foreign-key errors: {c['foreign_key_errors']}. The check preserved {c['baseline_metadata_IDs_preserved']:,} bound baseline identity/source/date/stratum/work-family/latest-version memberships. It verified {c['new_retained_Load_IDs_checked']:,} new retained SQL/Load IDs, their body/raw hashes, fixed dates and applicable original native mapping. Own raw/stored request objects were checked once; no old-body/raw corpus sweep was performed. Required public HTML/JSON pairs were checked from retained evidence. SQL delta and Load IDs are conserved, including separately typed supplements.",'',
 f"Cumulative transport/native counters are {s['cumulative_transport_targets']:,}/{s['cumulative_native_targets']:,}; maximum recorded native HTTP hops is {c['native_HTTP_hops_max']} against the inherited four-hop ceiling. Original counters, receipts, code bindings and controlled writer exits remain local. Actual-operation accounting preserved the shared 30 GB allowance, the social 15 GB envelope, the 15 GiB physical floor and 48 MiB recovery reserve. No restart extended the deadline. Resource results describe the actual snapshot, not guaranteed future physical capacity.",'',
 'The final frontier distinguishes discovered/queued, requested/touched, parsed, committed and observed-interface exhaustion. Remaining arrays and individual receipts stay local; finalized compact tables describe real source/era opportunities and access limits. Observed interface exhaustion does not prove that all historical editions exist in the corpus. The residual gap and legacy tables state unresolved work without replacing it with a score.','',
 'Monthly peaks are compared diagnostically with the preceding/following available three months, including incomplete boundary context. All legitimate peaks and raw evidence were retained; no event attribution, flattening or downsampling was performed. Record/title counts do not automatically equal independent works or publisher families. Parent dimensions remain auxiliary and do not control collection.','',
 'This delivery establishes dated source presence and readable text where verified. Climate/warming relevance and similarity, validated affect/risk associations, and fear-specific interpretation remain later evidence levels. Coverage, counts, query hits and model outputs do not establish emotion prevalence or a comparable three-role time series. No semantic corpus-wide labels or exclusion were run.','',
 '## Finalized delivery','',
 '- `DELIVERY_SUMMARY.json`, `CHANGED_TRANCHE_FINAL_CHECK.json`, `DELIVERY_FILE_RECEIPTS.json`: final counts, verification, sizes and hashes.',
 '- `ADDITIONAL_ARTICLE_REGISTER.csv`, `CURRENT_NEWSPAPER_ARTICLE_REGISTER.csv`, `NEWSPAPER_SUPPLEMENT_ARTICLE_REGISTER.csv`: retained identities with explicit frame separation.',
 '- `SOURCE_PROVENANCE_AND_DATE_REGISTER.csv`, `NEW_SOURCE_PURPOSE_GENRE_ERA_REGISTER.csv`: traceable date/native/raw and structural source metadata.',
 '- `MONTHLY_BEFORE_AFTER.csv`, `MONTH_SOURCE_COUNTS_BEFORE.csv`, `MONTH_SOURCE_COUNTS_AFTER.csv`, `SOURCE_YEAR_DELTA.csv`, `MONTH_PEAK_CONTEXT_FLAGS.csv`: regular-frame distribution.',
 '- `SUPPLEMENT_MONTH_SOURCE_COUNTS.csv`, `SUPPLEMENT_SOURCE_YEAR_DELTA.csv`, `COMBINED_FAMILY_MONTHLY_PRESENCE.csv`: separate supplement and alternative combined views.',
 '- `FRESH_ISSUE_TERMINAL_REGISTER.csv`, `LEGACY_AFFECTED_MONTH_BEFORE_AFTER.csv`, `LEGACY_TERMINAL_QUEUE_INVENTORY.csv`, `RESIDUAL_EMPTY_MONTHS.csv`, `SOURCE_FRONTIER_REGISTER.csv`, `PENDING_DISPOSITION_REGISTER.csv`, `HOST_STOP_REGISTER.csv`: real recovered and unresolved inventory.',
 '- `RAW_OBJECT_MANIFEST.csv`, `STRUCTURAL_UNIT_DISPOSITION_REGISTER.csv`, `HISTORICAL_CAMPUS_PRESERVATION_REGISTER.csv`: evidence preservation.',
 '', 'The coordinator owns publication and any future allocation. This collector has produced the factual local closed result and a lease-release request; it has not edited main, shared project logs or canonical coordination controls.','']
 return '\n'.join(lines).encode()
