"""One changed-tranche delivery after the single writer exits."""
import collections,csv,io,json,os
import elt
MONTHS=[f'{y:04d}-{m:02d}' for y in range(1988,2027) for m in range(1,13) if f'{y:04d}-{m:02d}'<='2026-09']
def lines(p):return [json.loads(s) for s in p.read_text().split('\n') if s] if p.exists() else []
def write_csv(name,data,fields):
 b=io.StringIO();w=csv.DictWriter(b,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(data);raw=b.getvalue().encode();elt.preflight(len(raw)*2+65536)
 p=elt.OWN/name;p.parent.mkdir(parents=True,exist_ok=True);tmp=p.with_name(p.name+'.pending');tmp.write_bytes(raw);tmp.replace(p)
def digest(p):
 h=elt.hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1048576),b''):h.update(b)
 return h.hexdigest()
def main():
 close=json.loads((elt.OWN/'COLLECTION_CLOSE_RECEIPT.json').read_text());assert close['writer_exit_observed'] and close['no_active_writer']
 try:os.kill(close['last_writer_pid'],0)
 except ProcessLookupError:pass
 else:raise RuntimeError('Collection writer still exists')
 elt.preflight(16*1024**2)
 accepted=json.loads((elt.PREVIOUS/'DELIVERY_FILE_RECEIPTS.json').read_text());snapshot=json.loads((elt.OWN/'INPUT_SNAPSHOT.json').read_text())
 baseline=list(csv.DictReader((elt.PREVIOUS/'ARTICLE_REGISTER.csv').open()));by_id={r['article_id']:r for r in baseline if r['disposition']=='confirmed_complete'};baseline_ids=set(by_id)
 transactions=lines(elt.OWN/'TRANSACTION_RECEIPTS.jsonl');history=lines(elt.OWN/'REQUESTS.jsonl');requests=list({r['target_id']:r for r in history}.values());receipts={r['target_id']:r for r in requests}
 consolidated={r['article_id'] for r in transactions if r['status']=='confirmed_complete' and r.get('baseline_TEXT_consolidation')};frozen_by_id=dict(by_id)
 new=[];pending=[];body_ok=True;raw_ok=True;baseline_digest_ok=True
 with elt.LOCK.open('a+b') as lock:
  elt.fcntl.flock(lock,elt.fcntl.LOCK_EX);c=elt.connect();c.row_factory=elt.sqlite3.Row
  qualified=c.execute('SELECT a.*,v.provenance_json,v.body_reference,v.raw_reference,length(v.body_text) AS body_chars,length(CAST(v.body_text AS BLOB)) AS body_bytes FROM articles a JOIN article_versions v ON v.version_id=a.latest_version_id LEFT JOIN article_dispositions d ON d.article_id=a.article_id WHERE d.article_id IS NULL').fetchall()
  for q in qualified:
   r=json.loads(q['provenance_json']);r.update(article_id=q['article_id'],publication_date=q['publication_date'],stratum=q['stratum'],work_family_id=q['work_family_id'],source_url=q['source_url'],disposition='confirmed_complete',whole_TEXT_characters=q['body_chars'],whole_TEXT_bytes=q['body_bytes']);by_id[r['article_id']]=r
   if r['article_id'] in consolidated:baseline_digest_ok &= r.get('body_sha256')==frozen_by_id[r['article_id']]['body_sha256']
   if r['article_id'] not in baseline_ids:
    new.append(r);bp=elt.REPO/q['body_reference'] if q['body_reference'] else None;rp=elt.REPO/q['raw_reference'] if q['raw_reference'] else None;raw_target=rp.name.removesuffix('.bin.gz') if rp else None;rec=receipts.get(raw_target);r['actual_raw_transport_target_id']=raw_target
    body_ok &= bool(bp and bp.exists() and bp.stat().st_size==q['body_bytes'] and q['body_chars']>0 and elt.eligible(q['publication_date']) and q['source_url'].startswith('https://'))
    raw_ok &= bool(rec and rec['status']=='saved' and rp and rp.exists() and rec['raw_reference']==q['raw_reference'] and rp.stat().st_size==rec.get('stored_bytes') and rec.get('raw_encoding')=='gzip' and rec.get('raw_sha256')==r.get('raw_sha256') and rec.get('stored_sha256')==r.get('stored_sha256') and rec.get('raw_bytes',0)<=elt.SCOPE['default_raw_object_cap_bytes'])
  counts=dict(article_rows_retained=c.execute('SELECT count(*) FROM articles').fetchone()[0],currently_qualified_article_rows=len(qualified),whole_text_versions=c.execute('SELECT count(*) FROM article_versions').fetchone()[0],separate_pending_or_component_records=c.execute('SELECT count(*) FROM evidence').fetchone()[0],reclassified_retained_article_rows=c.execute('SELECT count(*) FROM article_dispositions').fetchone()[0],baseline_metadata_rows=c.execute('SELECT count(*) FROM baseline').fetchone()[0])
  old_articles=c.execute('SELECT count(*) FROM articles WHERE first_loaded_at<=?',(snapshot['at_utc'],)).fetchone()[0];old_versions=c.execute('SELECT count(*) FROM article_versions WHERE loaded_at<=?',(snapshot['at_utc'],)).fetchone()[0]
  old_disp={r['article_id']:r['status'] for r in c.execute('SELECT article_id,status FROM article_dispositions')};expected={r['article_id']:r['disposition'] for r in baseline if r['disposition']!='confirmed_complete'}
  for q in c.execute('SELECT * FROM evidence WHERE loaded_at>?',(snapshot['at_utc'],)):
   r=json.loads(q['metadata_json']);pending.append(dict(evidence_id=q['evidence_id'],source_id=q['source_id'],source_url=q['source_url'],status=q['status'],publication_date=r.get('publication_date'),raw_reference=r.get('raw_reference'),body_reference=r.get('body_reference'),loaded_at_utc=q['loaded_at']))
  integrity=c.execute('PRAGMA quick_check').fetchone()[0]=='ok' and not c.execute('PRAGMA foreign_key_check').fetchall()
  latest_ok=c.execute('SELECT count(*) FROM articles a LEFT JOIN article_versions v ON v.version_id=a.latest_version_id WHERE v.version_id IS NULL OR v.article_id<>a.article_id').fetchone()[0]==0;c.close()
 combined=list(by_id.values());fields=list(baseline[0])+['raw_encoding','stored_sha256','stored_bytes','raw_bytes','whole_TEXT_characters','whole_TEXT_bytes','actual_raw_transport_target_id','request_id','html_raw_reference','publisher_timestamp','date_field','url_date','date_limit','byline','syndication_notices','historical_body_equivalence','retention','semantic_labels_executed','length_filter_used'];write_csv('ADDITIONAL_ARTICLE_REGISTER.csv',new,fields);write_csv('CUMULATIVE_ARTICLE_REGISTER.csv',combined,fields)
 write_csv('NEW_PENDING_OR_COMPONENT_REGISTER.csv',pending,['evidence_id','source_id','source_url','status','publication_date','raw_reference','body_reference','loaded_at_utc'])
 families=collections.defaultdict(set);ids=collections.defaultdict(set)
 for r in combined:
  for g in ['pooled',r['stratum']]:families[(g,r['publication_date'][:7])].add(r['work_family_id']);ids[(g,r['publication_date'][:7])].add(r['article_id'])
 coverage={};residual=[];lf=['month','stratum','complete_native_article_IDs','complete_independent_articles','months_at_minimum_coverage','additional_articles_required','partial_publication_month']
 for geo in ['pooled']+elt.SCOPE['strata']:
  ledger=[]
  for m in MONTHS:
   n=len(families[(geo,m)]);r=dict(month=m,stratum=geo,complete_native_article_IDs=len(ids[(geo,m)]),complete_independent_articles=n,months_at_minimum_coverage=n>=2,additional_articles_required=max(0,2-n),partial_publication_month=m=='2026-09');ledger.append(r)
   if n<2:residual.append(r)
  slug='pooled' if geo=='pooled' else geo.replace('/','_').replace(' ','_');write_csv('coverage/MONTHLY_'+slug+'.csv',ledger,lf)
  coverage[geo]=dict(months_at_minimum_coverage=sum(r['months_at_minimum_coverage'] for r in ledger),one_article_months=sum(r['complete_independent_articles']==1 for r in ledger),zero_article_months=sum(r['complete_independent_articles']==0 for r in ledger),article_count_distribution=dict(collections.Counter(r['complete_independent_articles'] for r in ledger)))
 write_csv('RESIDUAL_MONTHS.csv',residual,lf)
 manifest=json.loads((elt.OWN/'QUEUE_MANIFEST.json').read_text());inv=collections.defaultdict(lambda:[0,0])
 for r in manifest['source_year_inventory']:inv[(r['source_id'],r['year'])][0]+=r['observed_candidate_links']
 staged=collections.defaultdict(set)
 for p in (elt.OWN/'queues').glob('*.json'):
  for t in json.loads(p.read_text()):staged[(t['source_id'],t['month'][:4])].add(elt.canon(t['url']))
 for k,v in staged.items():inv[k][1]=len(v)
 inventory=[dict(source_id=s,year=y,frozen_observed_candidate_links=n[0],successor_staged_candidate_links=n[1],observed_candidate_links=sum(n),scope='Observed candidate metadata; source-year population and archive completeness unknown') for (s,y),n in sorted(inv.items())]
 write_csv('SOURCE_YEAR_INVENTORY.csv',inventory,['source_id','year','frozen_observed_candidate_links','successor_staged_candidate_links','observed_candidate_links','scope'])
 tp=[dict(at_utc=r.get('finished_at_utc'),target_id=r['target_id'],source_id=r['source_id'],source_url=r['url'],status=r['status'],receipt_reference='receipts/'+r['target_id']+'.json') for r in requests if r['status']!='saved'];write_csv('NEW_PENDING_TRANSPORT.csv',tp,['at_utc','target_id','source_id','source_url','status','receipt_reference'])
 raw_objects=[{k:r.get(k) for k in ['target_id','source_id','purpose','status','raw_reference','raw_sha256','raw_bytes','raw_encoding','stored_sha256','stored_bytes','partial','finished_at_utc']} for r in requests if r.get('raw_reference')];write_csv('RAW_OBJECT_MANIFEST.csv',raw_objects,['target_id','source_id','purpose','status','raw_reference','raw_sha256','raw_bytes','raw_encoding','stored_sha256','stored_bytes','partial','finished_at_utc'])
 opportunities=collections.Counter((r['stratum'],r['planned_lane']) for r in lines(elt.OWN/'OPPORTUNITY_LOG.jsonl'));elt.preparation_save('OPPORTUNITY_SUMMARY.json',{'at_utc':elt.utc(),'prospective_counts':[dict(stratum=g,recovery=opportunities[(g,'recovery')],production=opportunities[(g,'production')]) for g in elt.SCOPE['strata']],'qualification':'Planned opportunities, including unavailable sources; not acquired-body counts, sample weights or equal observed yields','restarts_reset_local_iteration_only':True,'cumulative_attempts_not_reset':True})
 startup=json.loads((elt.OWN/'STARTUP_CHECK.json').read_text());state=elt.state();external=elt.external_discovery_counts()
 attempts={g:dict(cumulative_native_article_targets=state['strata'][g]['article'],state_discovery_targets=state['strata'][g]['discovery'],unfolded_external_discovery_targets=external[g],effective_cumulative_discovery_targets=elt.effective_count(state,g,'discovery'),article_ceiling=6000,discovery_ceiling=1000) for g in elt.SCOPE['strata']}
 stops=[dict(host=h,stop=json.dumps(v,ensure_ascii=False),scope='Preserved inherited or observed publisher/access stop; no bypass/retry') for h,v in state['access_stops'].items()];write_csv('HOST_STOP_REGISTER.csv',stops,['host','stop','scope'])
 resource=elt.resource();checks=dict(accepted_changed_startup_check=startup['all_passed'],database_integrity=integrity,latest_version_mapping=latest_ok,old_400_articles_preserved=old_articles==400,old_402_versions_preserved=old_versions==402,old_eight_dispositions_preserved=len(expected)==8 and all(old_disp.get(a)==s for a,s in expected.items()),changed_TEXT_dates_links_sidecar_sizes=body_ok,changed_raw_receipts_encoding_digests_sizes=raw_ok,six_465_month_ledgers=len(coverage)==6 and len(MONTHS)==465,fixed_cutoff=elt.SCOPE['publication_interval']==['1988-01-01','2026-09-21'],cumulative_regional_ceilings=all(a['cumulative_native_article_targets']<=6000 and a['effective_cumulative_discovery_targets']<=1000 for a in attempts.values()),native_hops_within_four=all(n<=4 for n in state.get('native_http_hops',{}).values()),no_in_progress_transport=all(v!='in_progress' for v in state['targets'].values()),writer_exit_verified=True,ODT_policy_stop_preserved='www.odt.co.nz' in state['access_stops'],InDaily_asset_stop_preserved='assets.indailysa.com.au' in state['access_stops'],no_new_semantic_or_length_gate=all(r.get('semantic_labels_executed') is False and r.get('length_filter_used') is False for r in new),cumulative_media_cap=resource['cumulative_bytes']<5000000000)
 p=elt.OWN/'INDAILY_CHANGED_ADAPTER_CHECK.json'
 if p.exists():checks['named_InDaily_adapter_check']=json.loads(p.read_text())['all_passed']
 p=elt.OWN/'RECOVERY_DISCOVERY_CHANGE_CHECK.json'
 if p.exists():checks['targeted_recovery_discovery_change_check']=json.loads(p.read_text())['all_passed']
 p=elt.OWN/'DELIVERY_LOG_PARSER_CHECK.json'
 if p.exists():checks['named_JSONL_separator_check']=json.loads(p.read_text())['all_passed']
 checks['baseline_TEXT_consolidation_digest_matches_frozen_register']=baseline_digest_ok and len(consolidated)<=141
 consolidated={r['article_id'] for r in transactions if r['status']=='confirmed_complete' and r.get('baseline_TEXT_consolidation')};dimensions={k:dict(collections.Counter(str(r.get(k) or 'unrecorded') for r in combined)) for k in ['source_id','stratum','source_frame','genre','provenance']}
 summary=dict(at_utc=elt.utc(),status='production_tranche_delivered',publication_interval=elt.SCOPE['publication_interval'],deadline_unchanged=elt.SCOPE['hard_deadline_at_utc'],collection_close=close,cumulative_cap_bytes=5000000000,baseline_complete_IDs=533,additional_qualified_IDs=len(new),additional_qualified_source_mix=dict(collections.Counter(r['source_id'] for r in new)),cumulative_selected_complete_IDs=len(combined),whole_TEXT_database_counts=counts,baseline_TEXT_consolidated=len(consolidated),database=str(elt.DB.relative_to(elt.REPO)),coverage=coverage,cumulative_metadata_dimensions=dimensions,cumulative_attempt_counts=attempts,new_distinct_transport_target_receipts=len(requests),transport_history_rows=len(history),transport_history_reconciliation_rows=len(history)-len(requests),new_body_transfer_targets=sum(r['purpose']=='article' for r in requests),new_distinct_charged_article_targets=sum(r['purpose']=='article' and r.get('new_distinct_target_charge',False) for r in requests),new_HTTP_hops=sum(len(r.get('hops',[])) for r in requests),new_transport_statuses=dict(collections.Counter(r['status'] for r in requests)),new_separate_pending_or_component_records=len(pending),resource_at_delivery=resource,checks=checks,all_changed_tranche_checks_passed=all(checks.values()),accepted_pre_append_database_snapshot_receipt=accepted['files']['newspaper_elt.sqlite3'],old_payloads_rescanned=False,semantic_labels_executed=False,production_stops_at_two=False,milestone_is_guarantee_or_stop=False,independence_limit='Native article parents and known exact-body work families; remaining syndication and original-work relationships unresolved',source_year_inventory_scope='Observed native candidates, not complete source-year populations',genre_scope='Recorded native genre metadata only; missing retained as unrecorded',verification_scope='Changed identity/date/link/body/receipt mapping and one store integrity check; no universal historical-version, quotation-origin or claim-truth verification')
 elt.preparation_save('DELIVERY_SUMMARY.json',summary);pooled=coverage['pooled']
 coverage_table='\n'.join('| '+g+' | '+str(v['months_at_minimum_coverage'])+' | '+str(v['one_article_months'])+' | '+str(v['zero_article_months'])+' |' for g,v in coverage.items())
 report=f'''# Newspaper production continuation: package 26

Delivered snapshot: {summary['at_utc']}. The sole collection writer has exited. Closure reason: {close['reason']}. The absolute deadline remains {elt.SCOPE['hard_deadline_at_utc']} (7 October 00:20:21 CST). The publication interval remains 1988-01-01 through 2026-09-21; September 2026 is partial. Narrower source observation times remain: the day cutoff does not establish end-of-day completeness.

This tranche adds **{len(new)} qualified whole-article IDs**, beyond the frozen 533-ID selected baseline. The cumulative selected register has **{len(combined)} complete native article IDs**. The durable store has **{counts['currently_qualified_article_rows']} qualified whole-TEXT article IDs**, {counts['whole_text_versions']} retained body versions and {counts['separate_pending_or_component_records']} separate pending/component evidence records. **{len(consolidated)}** previously accepted external baseline bodies were consolidated into TEXT, separately from new acquisition. The old 400 article rows, 402 versions and eight dispositions remain preserved. The predecessor database hash denotes the accepted pre-append snapshot; one new final store hash accompanies delivery, without copying the database.

Pooled months at minimum coverage: **{pooled['months_at_minimum_coverage']}/465**, compared with 176/465 in the accepted input. There are {pooled['one_article_months']} one-article months and {pooled['zero_article_months']} zero-confirmed months. Six ledgers retain all 465 calendar months. Full-period acquisition remains incomplete. Zero-confirmed denotes this observed snapshot, not absence of newspaper discourse. Existence, digitisation, access and recoverable eras differ by title. Pooled presence does not certify each stratum or complete archives.

| Source stratum | Months with at least two articles | One-article months | Zero-confirmed months |
| --- | ---: | ---: | ---: |
{coverage_table}

All rows use the same 465-month calendar. The article independence rule and its unresolved syndication limits are described below.

A progress metadata snapshot at 14:06 UTC showed pooled 180/465 months at the minimum while most added articles increased density in inherited months. A targeted four-case memory check then supported advancing native discovery in recovery slots after all queued months for that source reach the recorded floor; production slots keep eligible further articles. The same writer restarted immediately with unchanged attempts, source stops, limits and deadline. The coverage metadata helper briefly blocked itself on a nested mutex; only that helper was interrupted, and its corrected read-only snapshot released the mutex before saving. These corrections remain documented without a repeated content/integrity audit.

Two whole articles/month remains a floor. Third, fourth and later eligible articles were retained; native issue discovery likewise continues beyond the floor. Ten prospective work opportunities allocate three to calendar recovery and seven to continuing production in one pipeline. The five regions retain equal cumulative ceilings of 6,000 native article targets and 1,000 discovery targets each, without transferring unused opportunities. Planned effort is not an inclusion weight or a promise of equal yield. The 10,000-addition milestone is reporting only, with no stop or guarantee.

Article IDs, native charged targets, body-transfer targets, HTTP hops, discovery and accepted TEXT consolidation are separately reported. There are {len(requests)} distinct new transport target receipts and{len(history)} history rows; final transport totals collapse reconciliation history by target identity. Restarts preserved interrupted attempts. Saved metadata candidates are not acquired articles until a complete body passes structural/date/identity mapping and is immediately Loaded.

Retained source frames include Irish/British/US student newspapers, Australian advocacy press, InDaily's South Australian newspaper-brand digital successor and pre-stop Otago Daily Times material. InDaily retains its Independent Weekly print/digital break; CityMag, SALIFE and InReview remain separate. Its inherited asset-host 403 is preserved. Nine named retained sitemap payloads supply unused native article links without a stopped-host request. FIRST_INDAILY_BODY_CHECKPOINT.json records a new committed whole body with separate native publication/update times and raw digests. A single named changed-adapter fixture matched accepted body evidence; the accepted seventeen-check startup suite was not rerun. An overlooked inherited asset stop caused a brief worker exit; its error, correction and immediate same-task restart remain traceable.

New authoritative [ODT/Allied Media platform terms](https://alliedmedia.co.nz/platform-terms-of-use/), dated 23 July 2026, prohibit automated collection/extraction and database compilation without written consent. ODT/Allied hosts were stopped immediately on observing that evidence. Pre-stop raw, bodies and frozen qualification evidence remain preserved; reuse/retention permission review is pending. Other historical/general-interest routes retain rights, subscription, key, robots or transport limits. Critic identifies itself as a student magazine and was not relabelled as a newspaper. National Library Waitomo News metadata evidences a historical newspaper/PDF route and separate King Country News successor; rights and issue/article mapping remain pending. Neither candidate was activated or counted as acquired.

SOURCE_YEAR_INVENTORY.csv separates frozen and successor-staged candidate counts; it does not claim full title-year populations. Native cursors, dates, content-version times, source frames, article parents and known exact-body families remain available. The ledger field complete_independent_articles uses the retained native-parent/known exact-body family rule; broader wire/syndication/mirrored-work independence remains unresolved. Directness is relative to the newspaper utterance: original publisher text is direct publication evidence, and print scans are archival reproduction. Neither establishes truth of every claim, historical equivalence of today's archive body or origin/holder of every quotation. Genre/provenance tallies use recorded metadata only; missing genre remains unrecorded.

The cumulative cap is exactly **5,000,000,000 bytes decimal**, including earlier media and all five disjoint accounting roots. Accounted bytes at the delivery resource snapshot: **{resource['cumulative_bytes']:,}**. Actual destination free bytes: **{resource['free_bytes']:,}**. Physical headroom after the protected 15 GiB floor, 48 MiB recovery allowance and live lease/receipt accounting: **{resource['physical_headroom']:,}**. Each operation protected the full database rollback-journal bound, original raw object, compressed storage, body/TEXT growth and other actual leases. Raw gzip retains distinct original-byte/stored-object digests and the uncompressed 2 MiB cap. No new historical PDF issue was transferred.

The initial physical stop remains in history/PHYSICAL_BLOCK_20261006T123703.json. The digest-bound capacity release and worker receipt record the meaningful space increase; no floor/recovery waiver, deleted-evidence credit, budget reset or clock extension occurred. Final changed-tranche checks passed: **{all(checks.values())}**. They verify changed TEXT/date/link/reference sizes and ingested receipt digests without a raw/body hash sweep, one consolidated SQLite integrity/foreign-key check and bounded old-row metadata preservation. The final database hash is one delivery snapshot.

Additional/cumulative article registers, six monthly ledgers, residual months, source-year inventory, pending/component and transport registers, host stops, process/restart/first-body checkpoints, resource and file receipts accompany delivery. Coordinator control/PROJECT_LOG files were not edited. No government reopening, social-media collection, evaluator access, third-party message, worker Git, new chat, delegated agent or automation occurred.

These are dated-source/readable-text and structural acquisition results. Climate relevance/similarity, affect/risk/future-harm association and fear-specific attribution remain later validated stages. Coverage and volume do not establish emotion prevalence or a comparable three-role fear time series.
'''
 payload=report.encode();elt.preflight(len(payload)*2);(elt.OWN/'DELIVERY_REPORT.md').write_bytes(payload)
 elt.preparation_save('WORKER_COMPLETION.json',dict(at_utc=elt.utc(),status=summary['status'],new_article_IDs=len(new),no_active_background_worker=True,all_changed_tranche_checks_passed=all(checks.values()),control_and_lease_reconciliation='Coordinator-owned; no control edited',deadline_unchanged=elt.SCOPE['hard_deadline_at_utc']))
 names=['elt.py','indaily.py','extract_load.py','production.py','startup_check.py','deliver.py','STARTUP_CHECK.json','QUEUE_MANIFEST.json','SOURCE_YEAR_INVENTORY.csv','SOURCE_READINESS.json','NATIVE_CURSORS.json','TRANSPORT_STATE.json','GL_ISSUE_QUEUE.json','INPUT_SNAPSHOT.json','DELIVERY_REPORT.md','DELIVERY_SUMMARY.json','ADDITIONAL_ARTICLE_REGISTER.csv','CUMULATIVE_ARTICLE_REGISTER.csv','RESIDUAL_MONTHS.csv','NEW_PENDING_TRANSPORT.csv','NEW_PENDING_OR_COMPONENT_REGISTER.csv','HOST_STOP_REGISTER.csv','WORKER_COMPLETION.json','COLLECTION_CLOSE_RECEIPT.json','WORKER_PROCESS.json','CAPACITY_RESUME_WORKER_RECEIPT.json','FIRST_REAL_COLLECTION_CHECKPOINT.json','FIRST_INDAILY_BODY_CHECKPOINT.json','INDAILY_ACTIVATION.json','INDAILY_CHANGED_ADAPTER_CHECK.json','INDAILY_RESTART_RECEIPT.json','INDAILY_STOP_CORRECTION_RECEIPT.json','ODT_NEW_POLICY_STOP.json','POLICY_RESTART_RECEIPT.json','RESUME_CODE_AMENDMENT.json','REQUESTS.jsonl','TRANSACTION_RECEIPTS.jsonl','PRODUCTION_CHECKPOINT.json','PRODUCTION_CHECKPOINT_HISTORY.jsonl','OPPORTUNITY_LOG.jsonl','EXECUTION_ERROR.json','EXECUTION_STOP.json']
 names+=['RAW_OBJECT_MANIFEST.csv','OPPORTUNITY_SUMMARY.json','LOAD_LOG.jsonl','FRONTIER_STOPS.jsonl','METADATA_HELPER_LOCK_CORRECTION.json','CALENDAR_PROGRESS_20261006T1403.json','CALENDAR_PROGRESS_20261006T1502.json','RECOVERY_DISCOVERY_CHANGE_CHECK.json','RECOVERY_DISCOVERY_RESTART_RECEIPT.json','DISCOVERY_SOURCE_STOPS.jsonl','DELIVERY_LOG_PARSER_CHECK.json']
 paths=[elt.OWN/n for n in names if (elt.OWN/n).exists()]+list((elt.OWN/'coverage').glob('*.csv'))+list((elt.OWN/'history').glob('*.json'))+list(elt.OWN.glob('EXTERNAL_SOURCE_PREPARATION_RECEIPT_*.json'))+list((elt.OWN/'queues').glob('*.json'))+list((elt.OWN/'receipts').glob('*.json'))+list((elt.OWN/'targets').glob('*.json'))
 hashes={str(p.relative_to(elt.OWN)):dict(sha256=digest(p),bytes=p.stat().st_size) for p in paths};hashes[str(elt.DB.relative_to(elt.REPO))]=dict(sha256=digest(elt.DB),bytes=elt.DB.stat().st_size)
 elt.preparation_save('DELIVERY_FILE_RECEIPTS.json',dict(at_utc=elt.utc(),files=hashes,raw_body_hash_sweep=False,final_database_hashed_once=True,accepted_pre_append_database_receipt=accepted['files']['newspaper_elt.sqlite3']))
 print(json.dumps({k:summary[k] for k in ['status','additional_qualified_IDs','cumulative_selected_complete_IDs','baseline_TEXT_consolidated','all_changed_tranche_checks_passed']}))
if __name__=='__main__':main()
